%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/kunalmenda/Google Drive/2016 Spring/E160/E160/Lab4/1000_KSL3.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/03/31 20:55:41

%% Initialize variables.
filename = '/Users/kunalmenda/Google Drive/2016 Spring/E160/E160/Lab4/3000_USL1.txt';
delimiter = ' ';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
time = dataArray{:, 1};
x = dataArray{:, 2};
y = dataArray{:, 3};
t = dataArray{:, 4};
x_est = dataArray{:, 5};
y_est = dataArray{:, 6};
t_est = dataArray{:, 7};
x_var = dataArray{:, 8};
y_var = dataArray{:, 9};
xv_covar = dataArray{:, 10};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;